spring.application.name=mapleinfo
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/maple_info?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=dongyang

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

key=live_e0ddc15f7be765a271f1a6eda9638b3a58e2fc30ec3968f0f715efa25f94d1e1efe8d04e6d233bd35cf2fabdeb93fb0d

jwt.secret=7f8a9e2d5b6c31a4f0d6e8b19a2c3f4e5d6c7b8a9f0e1d2c3b4a5f6e7d8c9b0a