spring.application.name=mapleinfo
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/maple_info?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=dongyang

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

key=test_e0ddc15f7be765a271f1a6eda9638b3ab15056b1dc7472b33ae3b87e66b5c64cefe8d04e6d233bd35cf2fabdeb93fb0d